const ExpenseActionTypes = {
  LIST_REQUEST: "EXPENSE_LIST_REQUEST",
  LIST_SUCCESS: "EXPENSE_LIST_SUCCESS",
  LIST_FAIL: "EXPENSE_LIST_FAIL",
  CREATE_REQUEST: "EXPENSE_CREATE_REQUEST",
  CREATE_SUCCESS: "EXPENSE_CREATE_SUCCESS",
  CREATE_FAIL: "EXPENSE_CREATE_SUCCESS",
  DELETE_REQUEST: "EXPENSE_DELETE_REQUEST",
  DELETE_SUCCESS: "EXPENSE_DELETE_SUCCESS",
  DELETE_FAIL: "EXPENSE_DELETE_FAIL",
};

export default ExpenseActionTypes;